services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app_hotel_booking
    volumes:
      - .:/var/www:cached
      - vendor_data:/var/www/vendor
    working_dir: /var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: hotel_booking_nginx
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: hotel_booking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=256M

  redis:
    image: redis:7.2.5-alpine
    container_name: hotel_booking_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 77447
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  mysql_data:
  vendor_data:
  redis_data: